### ISSUE TITLE
[Enhancement Request] Make Alembic available via Sketchpacks

### ISSUE THREAD

**Issue by adamkirkwood** [awkward/Alembic#2]
Sketchpacks allows you to publish your plugin to a public Sketch plugin registry, making it easy for Sketchpacks users to one-click install your plugin from anywhere on the web.

You can [read our docs about publishing plugins](https://docs.sketchpacks.com/developers/publishing.html) to the Sketchpacks registry for more details.

**Comment by marcbouchenoire** [comment]
Thank you for your suggestion, we're not installing any Github integrations for now, is there any other way that we could add Alembic to Sketchpacks?

**Comment by adamkirkwood** [comment]
@bouchenoiremarc Sketchpacks scrapes entries added to https://github.com/sketchplugins/plugin-directory once a day.

For our own feedback, what parts of Sketchpacks Relay does not interest you in installing it?

**Comment by marcbouchenoire** [comment]
Thanks! We prefer to maintain updates ourselves so having an integration do that would be redundant.
