### ISSUE TITLE
Unable to launch the plugin

### ISSUE THREAD

**Issue by angelfu528** [awkward/Alembic#3]
Hey there - I don't use sketch runner, so I just downloaded the plugin directly. I was trying to launch it following the instructions, but I wasn't able to find the plugin in the dropdown menu. 

Is there something I am missing during the process?

**Comment by marcbouchenoire** [comment]
Hey @angelfu528, it looks like you are missing a step in the installation indeed. Make sure to double-click the downloaded file `Alembic.sketchplugin` to install it. [https://sketchapp.com/learn/documentation/plugins/](https://sketchapp.com/learn/documentation/plugins/)
